### ISSUE TITLE
Apply an Open Source license?

### ISSUE THREAD

**Issue by etlacker** [soulshined/vscode-jump-to-character-position#1]
Hey, can you apply an open source license to this utility so that I can get it approved for use at my place of work? It has been immensely useful debugging legacy SQL queries.

**Comment by soulshined** [comment]
@etlacker thanks for the feedback! I have added MIT license per your request. If it needs to be a part of the actual vscode release, I will have to do that when I get home later after work. Let me know if you need anything else.

Cheers

**Comment by etlacker** [comment]
Awesome! I think just the MIT license is good enough. Thanks for the quick response!
