### ISSUE TITLE
Get Position Of Curser - Reverse Of Going To A Position

### ISSUE THREAD

**Issue by sahin52** [soulshined/vscode-jump-to-character-position#2]
A feature request:  
Going to character position is awesome, but it'd be nice to get the current position of cursor.

**Comment by soulshined** [comment]
@sahin52 

Just making sure we are thinking about the same thing:

vscode does provide the position of a cursor at the bottom of the status bar where it says something like Ln 58, Col 31:

![Screenshot 2022-03-04 165013](https://user-images.githubusercontent.com/11242654/156852618-23589616-bd91-4d5b-a0c6-e19725c2a862.png)

Col 31 would be the column of the cursor.

Are you talking about that or do you want the 'absolute index'? Like the 0 or 1 based character index in the text body?

**Comment by sahin52** [comment]
We can jump to a character position, by giving the number of exact position in that file with your extension. I want my exact position currently, not the line and column.  
Let me show you what I mean:  
I can go to a position (1234th char) with your extension like this:  
![image](https://user-images.githubusercontent.com/39086573/156854702-4b3921c2-649d-4df4-a143-fcc93bb0817a.png)
  
And I have gone here:  
![image](https://user-images.githubusercontent.com/39086573/156854745-7662f104-8771-4e63-b1b7-430e770a4b49.png)
  For example when I didn't change my position after going to a position(1234) and if I want to get my position here, somehow I need to get 1234.  

I didn't think how it would show, with a dialog box or something. I just would be happy if I get my position. It is important when dealing with files and texts in them.

**Comment by soulshined** [comment]
Great. Thanks for walkthrough and snapshots! Much appreciated. I think we are on the same page!

Getting a characters position is not a terribly complex task to do at all, however, if we are to take user experience into account, there's really only 2 ways I can think of that vscode api natively supports.

1) Getting the position with an `onkeypress`-like event handler
2) Getting the position using an interval timer (which I'm not particular excited about personally)

Both these options, at a high level, could potentially negatively impact editor performance and I would like to avoid that, if possible. Not to say that it will, just saying I don't know off the top of my head.

Worst case scenario, I can just add a command pallete command that the user will have to explicitly invoke, something along the lines of what you mentioned with a dialog box.

All this to say, it's doable, and I find value in adding it, I just want to make sure it's done in a way that doesn't have a negative experience as a byproduct so it won't be as fast as a turn-around as you would like I image. But let me explore those first 2 options and see how they impact typing performance, if at all, and go from there!

**Comment by soulshined** [comment]
This was easier than I anticipated @sahin52 

Please udpate your extension to 2.0, review the [changelog](https://github.com/soulshined/vscode-jump-to-character-position/blob/master/CHANGELOG.md#v20) for details around it and provide feedback on if I should close this or not

**Comment by sahin52** [comment]
Thanks a lot, it seems quite okay. I personally would want a key press to see my current location, like for example when I press Ctrl+k Ctrl+g. I could see my current position under the dialog box when I could write the position that I want to go. 
![image](https://user-images.githubusercontent.com/39086573/156904787-7d224bea-0f53-435f-87f7-fb083435845b.png)
Here can show "Your current position is 123" for example under the input area.    
But this version is completely okay as well, it is just my personal opinion. Thank a lot again.
