### ISSUE TITLE
What are the shortcuts on Mac?

### ISSUE THREAD

**Issue by benedikt-buchert** [soulshined/vscode-jump-to-character-position#3]

**Comment by relative** [comment]
[<kbd>⌘+K</kbd> <kbd>⌘+G</kbd>](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor)

**Comment by benedikt-buchert** [comment]
Oh, thank you can we add to the docs?

**Comment by benedikt-buchert** [comment]
Thanks a lot for the plugin helped me a ton!

**Comment by soulshined** [comment]
Thank you for the feedback @benedikt-buchert sincerely much appreciated!

You can also just type any extension name in the Keyboard Shortcuts Editor relative was nice enough to link above; just fyi. That way you can also see if there are *not* default keybinds applied and you can add/edit one.
