### ISSUE TITLE
How to use in Windows?

### ISSUE THREAD

**Issue by hornta** [soulshined/vscode-jump-to-character-position#5]
~~I'm trying to use this on Windows. I'm holding `ctrl`, then I press and hold `k` and then I press and hold `g`. Is something supposed to happen because I don't get any popup where I can enter the position.~~

PEBKAC

**Comment by soulshined** [comment]
glad to hear PEBKAC! I've also had some weird issues with keybinds and PowerToys so it never hurts to ask!
